name: Deploy to GitHub Pages

on:
  push:
    branches: [ Ionut-Gardu ]
  pull_request:
    branches: [ Ionut-Gardu ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/Ionut-Gardu'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless

    - name: Deploy to GitHub Pages
      run: ng deploy --base-href=/Ionut-gardu/ --name="GitHub Actions" --email="action@github.com"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
