name: Deploy to GitHub Pages

# Controls when the action will run
on:
  push:
    branches: 
      - Ionut-Gardu
  pull_request:
    branches:
      - Ionut-Gardu
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -- --configuration production

      # Copy files from browser subfolder to expected location
      - name: Prepare files for deployment
        run: |
          mkdir -p dist/tt-project-deploy
          cp -r dist/tt-project/browser/* dist/tt-project-deploy/
          cp dist/tt-project/browser/index.html dist/tt-project-deploy/404.html
          
      - name: Deploy to GitHub Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: production
          base_href: /Ionut-gardu/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/tt-project-deploy
          skip_build: true
